baseurl: /incubator-repo
exclude: ['README.md']
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      proj-name: "Project Newcastle"
      proj-abbrev: "PNC"
collections:
  - services
